name: Main Workflow
on:
  repository_dispatch:
  workflow_dispatch:
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Main job completed."
      - name: Trigger secondary workflow
        uses: actions/github-script@v6
        with:
          script: |
            const actionCore = require('@actions/core');
            const ghInstance = require('@actions/github');
            const { myContext } = ghInstance;
            await ghInstance.rest.actions.createWorkflowDispatch({
              owner: myContext.repo.owner,
              repo: myContext.repo.repo,
              workflow_id: 'secondary-workflow.yml',
              ref: myContext.ref,
            });
