name: Upload Config File
on:
  workflow_dispatch:
  repository_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Copy config file to test directory
        run: |
          cp build/config.github/workspace/test/
      - name: Commit and push changes
        run: |
          git config --global user.email "your_email@example.com"
          git config --global user.name "Your Name"
          git add.github/workspace/test/config
          git commit -m "Upload config file to test directory"
          git push
