name: Trigger Another Workflow

on:
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger another workflow
        run: |
          curl -X POST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/shenxianpeng/shenxianpeng/actions/workflows/YOUR_WORKFLOW_FILE.yml/dispatches \
          --data '{"ref": "main", "event_type": "special_repository"}'
