name: OpenWrt Builder-7981r128

on:
  repository_dispatch:
  workflow_dispatch:


jobs:
  read-and-set:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read values from setting.ini and set environment variables
        run: |
          cd build
          SOURCE_CODE=$(grep "SOURCE_CODE" setting.ini | cut -d'=' -f2)
          REPO_URL=$(grep "REPO_URL" setting.ini | cut -d'=' -f2)
          REPO_BRANCH=$(grep "REPO_BRANCH" setting.ini | cut -d'=' -f2)
          DEVICE_NAME=$(grep "DEVICE_NAME" setting.ini | cut -d'=' -f2)
          DIY_P1_SH=$(grep "DIY_P1_SH" setting.ini | cut -d'=' -f2)
          DIY_P2_SH=$(grep "DIY_P2_SH" setting.ini | cut -d'=' -f2)          
          echo "SOURCE_CODE=$SOURCE_CODE" >> $GITHUB_ENV
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
          echo "REPO_BRANCH=$REPO_BRANCH" >> $GITHUB_ENV
          echo "DEVICE_NAME=$DEVICE_NAME" >> $GITHUB_ENV
          echo "DIY_P1_SH=$DIY_P1_SH" >> $GITHUB_ENV
          echo "DIY_P2_SH=$DIY_P2_SH" >> $GITHUB_ENV  

      - name: Print environment variables
        run: |
          echo "SOURCE_CODE=$SOURCE_CODE"
          echo "REPO_URL=$REPO_URL"
          echo "REPO_BRANCH=$REPO_BRANCH"
          echo "DEVICE_NAME=$DEVICE_NAME"
          echo "DIY_P1_SH=$DIY_P1_SH"
          echo "DIY_P2_SH=$DIY_P2_SH"
