name: OpenWrt Builder-7981r128

on:
  repository_dispatch:
  workflow_dispatch:


jobs:
  read-and-set:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read values from setting.ini and set environment variables
        run: |
          cd build
          EC=$(grep "REPO_URL" setting.ini | cut -d'=' -f2)
          BD=$(grep "REPO_BRANCH" setting.ini | cut -d'=' -f2)
          echo "EC=$REPO_URL" >> $GITHUB_ENV
          echo "BD=$REPO_BRANCH" >> $GITHUB_ENV

      - name: Print environment variables
        run: |
          echo "REPO_URL value: ${{ env.REPO_URL }}"
          echo "REPO_BRANCH value: ${{ env.REPO_BRANCH }}"
