name: Secondary Workflow

on:
  repository_dispatch:
  workflow_dispatch:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed
    filters:
      branches:
        only: main  # 假设主分支，可根据实际情况调整
      events:
        - workflow_dispatch
      statuses:
        - success  # 仅当主工作流成功时才触发副工作流
jobs:
  secondary-job:
    runs-on: ubuntu-latest
    steps:
      - name: Secondary Step
        run: echo "Secondary workflow step."
