name: Trigger Another Workflow

on:
  workflow_dispatch:  # 允许手动触发此工作流

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Trigger Another Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的令牌
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ShmilyStar/OpenWrt-Actions-Compile/actions/workflows/编译固件.yml/dispatches \
            -d '{"ref":"main"}'
