name: Update Start File

on:
  workflow_dispatch:

jobs:
  update_start_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update start file with current date
        run: |
          # 确保 build 目录存在
          mkdir -p build
          # 更新 start 文件内容为当前日期
          echo "$(date +%Y年%m月%d号%H时%M分%S秒)" > build/start
          
          # 配置 Git
          git config --local user.name "ShmilyStar"  # 替换为你的用户名
          
          # 提交更改
          git add build/start
          git commit -m "Update start file with current date"
          
          # 推送更改
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
