# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-workflow-b:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Another Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 'conpile.yml'  # 目标工作流的文件名
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub Token
