name: Trigger Another Workflow

on:
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger another workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
            https://api.github.com/repos/ShmilyStar/OpenWrt-Actions-Compile/actions/workflows/编译固件.yml/dispatches \
            -d '{"ref":"main"}'
