name: test

on:
  repository_dispatch:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-22.04
    - name: 生成release标签
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=${{ env.SOURCE_CODE }}-${{ env.DEVICE_NAME }}-${{ env.FILE_DATE }}" >> $GITHUB_OUTPUT
        touch release.txt
        echo "${{ env.SOURCE_CODE }}-${{ env.DEVICE_NAME }}, lan: 192.168.8.1," >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT
