name: OpenWrt Builder-7981r128

on:
  repository_dispatch:
  workflow_dispatch:


jobs:
  read-and-set:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read values from setting.ini and set environment variables
        run: |
          REPO_URL=$(grep "REPO_URL" build/setting.ini | cut -d'=' -f2)
          REPO_BRANCH=$(grep "REPO_BRANCH" build/setting.ini | cut -d'=' -f2)
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
          echo "REPO_BRANCH=$REPO_BRANCH" >> $GITHUB_ENV

      - name: Print environment variables
        run: |
          echo "REPO_URL value: ${{ env.REPO_URL }}"
          echo "REPO_BRANCH value: ${{ env.REPO_BRANCH }}"
